import { ApplicationStatus, DocumentStatus, Language, VisaType, AppointmentStatus } from './types';

export const APP_ROUTES = {
  HOME: '/',
  AUTH: '/auth',
  LOGIN: '/auth',
  DASHBOARD: '/dashboard',
  ADMIN: '/admin',
  PROFILE: '/profile',
  VERIFY_EMAIL: '/verify-email',
};

const isProd = import.meta.env.MODE === 'production';
const origin = typeof window !== 'undefined' ? window.location.origin : '';
const isVercel = origin.includes('vercel.app');

export const API_ROUTES = {
  // In production behind nginx, the API is proxied under /api. In development point to backend port 4000 unless overridden.
  // If on Vercel, point directly to Render backend since Vercel can't proxy
  BASE_URL: import.meta.env.VITE_API_BASE_URL || (isProd ? (isVercel ? 'https://cavb-visa.onrender.com/api' : '/api') : 'http://localhost:4000/api'),
  AUTH: '/auth',
  APPLICATIONS: '/applications',
  ADMIN: '/admin',
  // WebSocket: prefer explicit env; else derive from current origin replacing http(s) with ws(s)
  WEBSOCKET:
    import.meta.env.VITE_WS_URL ||
    (isProd
      // On Vercel, default directly to Render WS since Vercel doesn't proxy WebSockets
      ? (isVercel ? 'wss://cavb-visa.onrender.com/ws' : origin.replace(/^http/, 'ws') + '/ws')
      // In development, use local WebSocket
      : 'ws://localhost:4000/ws'),
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    // General
    appName: "IOM - Brazil Visa",
    login: "Login",
    register: "Register",
    logout: "Logout",
    email: "Email Address",
    password: "Password",
    fullName: "Full Name",
    submit: "Submit",
    loading: "Loading...",
    // Plan Page
    planTitle: "Development & Database Plan",
    planIntro: "This document outlines the development plan and conceptual database schema for the CAVB IOM Haiti Brazil Visa Application Platform, as requested.",
    devPlanTitle: "Development Plan",
    phase1: "Phase 1: Core Foundation & Authentication",
    phase1Desc: "Build the user interface, multi-language support, authentication portal (Login/Register), and basic page structure.",
    phase2: "Phase 2: User Dashboard & Application Flow",
    phase2Desc: "Develop the user dashboard, visa type selection, appointment booking system, and document upload functionality.",
    phase3: "Phase 3: Backend Integration & Notifications",
    phase3Desc: "Connect the frontend to backend services, manage application states, and implement user notification systems.",
    dbSchemaTitle: "Conceptual Database Schema",
    dbSchemaDesc: "A simplified schema to support the application's functionality, focusing on users, applications, documents, and appointments.",
    usersTable: "Users Table",
    applicationsTable: "Applications Table",
    documentsTable: "Documents Table",
    appointmentsTable: "Appointments Table",
    proceedToApp: "Proceed to Application Demo",
    // Home Page
    welcomeTitle: "Welcome to the Brazil Visa Application Portal",
    welcomeSubtitle: "Facilitating visa requests for Haitian citizens through IOM.",
    vitemXI: "VITEM XI - Family Reunification Visa",
    vitemXIDesc: "For individuals who have family members residing in Brazil. This visa aims to reunite families and strengthen social bonds.",
    vitemIII: "VITEM III - Humanitarian Visa",
    vitemIIIDesc: "For Haitian nationals facing humanitarian crises, as established by Brazilian inter-ministerial ordinances.",
    getStarted: "Get Started",
    // Dashboard
    dashboardTitle: "My Application Dashboard",
    applicationStatus: "Application Status",
    applicationDetails: "Application Details",
    visaType: "Visa Type",
    createdAt: "Submission Date",
    documents: "Required Documents",
    docType: "Document Type",
    docStatus: "Status",
    docAction: "Action",
    fileName: "File Name",
    upload: "Upload",
    view: "View",
    appointment: "Your Appointment",
    noAppointment: "No appointment scheduled yet. Please upload all required documents to proceed.",
    scheduleAppointment: "Schedule Appointment",
    appointmentAt: "Appointment at",
    appointmentPromptApproved: "Your application is approved. Please schedule your appointment below.",
    appointmentPromptReview: "Your application is under review. Once approved, you will be able to schedule an appointment.",
    applicationRejectedMessage: "Your application has been rejected. No appointment can be scheduled.",
    // Statuses
    [ApplicationStatus.NOT_STARTED]: "Not Started",
    [ApplicationStatus.PENDING_DOCUMENTS]: "Pending Documents",
    [ApplicationStatus.IN_REVIEW]: "In Review",
    [ApplicationStatus.APPOINTMENT_SCHEDULED]: "Appointment Scheduled",
    [ApplicationStatus.APPROVED]: "Approved",
    [ApplicationStatus.REJECTED]: "Rejected",
    [DocumentStatus.MISSING]: "Missing",
    [DocumentStatus.UPLOADED]: "Uploaded",
    [DocumentStatus.VERIFIED]: "Verified",
    // Appointment Statuses
    [AppointmentStatus.BOOKED]: "Booked",
    [AppointmentStatus.CONFIRMED]: "Confirmed",
    [AppointmentStatus.COMPLETED]: "Completed",
    [AppointmentStatus.CANCELLED]: "Cancelled",
    // Visa Types
    [VisaType.VITEM_XI]: "VITEM XI (Family Reunification)",
    [VisaType.VITEM_III]: "VITEM III (Humanitarian)",
    selectVisaType: "Select Your Visa Program",
    startApplication: "Start Application",
    // Auth
    authPrompt: "Please log in or register to begin your application.",
    loginPrompt: "Already have an account?",
    registerPrompt: "Don't have an account?",
    fillAllFields: "Please fill in all fields.",
    invalidCredentials: "Invalid email or password.",
    registrationSuccess: "Registration successful! Please log in.",
    // Email verification
    registrationSuccessTitle: "Registration Successful!",
    accountCreatedMessage: "Your account has been created successfully. To complete the registration process:",
    verifyEmailRequired: "Email Verification Required",
    emailVerificationStep1: "Go to your Gmail inbox",
    emailVerificationStep2: "Look for the email from \"IOM Visa Application System\"",
    emailVerificationStep3: "Click the \"✅ Verify Email Address\" button",
    emailVerificationStep4: "Once verified, you can log in",
    emailSentTo: "Email sent to:",
    spamWarning: "⚠️ If you can't find the email, check your spam or junk folder.",
    gotItGoToLogin: "Got it, go to Login",
    apiError: "An error occurred. Please try again later.",
    fileUploaded: "File uploaded successfully.",
    appointmentBooked: "Appointment booked successfully.",
    // Enhanced Appointment Form
    dateOfBirth: "Date of Birth",
    passportNumber: "Passport Number",
    nationality: "Nationality",
    selectNationality: "Select Nationality",
    appointmentDate: "Appointment Date",
    appointmentTime: "Appointment Time",
    selectTime: "Select Time",
    bookAppointment: "Book Appointment",
    scheduling: "Scheduling...",
    appointmentRequirements: "Appointment Requirements",
    identityDocumentVerified: "Identity Document Verified",
    personalInfoComplete: "Personal Information Complete",
    identityDocumentRequired: "Identity Document must be verified before booking appointment",
    appointmentBookingNote: "Please ensure all information is correct. A confirmation letter will be generated after booking.",
    status: "Status",
    downloadLetter: "Download Letter",
    // Profile Page
    personalInformation: "Personal Information",
    security: "Security",
    phoneNumber: "Phone Number",
    address: "Address",
    enterYourAddress: "Enter your complete address",
    updateProfile: "Update Profile",
    updating: "Updating...",
    profileUpdatedSuccessfully: "Profile updated successfully",
    profileUpdateFailed: "Failed to update profile",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    changePassword: "Change Password",
    passwordsDoNotMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    passwordChangedSuccessfully: "Password changed successfully",
    passwordChangeFailed: "Failed to change password",
    passwordSecurityNote: "Password Security",
    passwordRequirements: "Your password must be at least 6 characters long and contain a mix of letters and numbers.",
    imageTooLarge: "Image file is too large. Maximum size is 5MB.",
    // Admin
    adminDashboard: "Admin Dashboard",
    allApplications: "All Applications",
    applicantName: "Applicant Name",
    applicantEmail: "Applicant Email",
    applicationId: "Application ID",
    reviewApplication: "Review Application",
    updateStatus: "Update Status",
    approve: "Approve",
    reject: "Reject",
    verify: "Verify",
    rejectionReason: "Rejection Reason",
    rejectionReasonPrompt: "Please provide a reason for rejection.",
    cancel: "Cancel",
    confirm: "Confirm",
    documentVerified: "Document Verified.",
    documentRejected: "Document Rejected.",
    applicationApproved: "Application Approved.",
    applicationRejected: "Application Rejected.",
    manageApplication: "Manage Application",
    approveApplication: "Approve Application",
    rejectApplication: "Reject Application",
    documentReview: "Document Review",
    noApplications: "No applications found.",
    rejectionNote: "Rejection Reason",
    // Calendar & Appointments
    appointmentManagement: "Appointment Management",
    calendar: "Calendar",
    list: "List",
    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    november: "November",
    december: "December",
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    more: "more",
    appointmentsFor: "Appointments for",
    noAppointmentsScheduled: "No appointments scheduled",
    reschedule: "Reschedule",
    rescheduleAppointment: "Reschedule Appointment",
    newDate: "New Date",
    newTime: "New Time",
    appointmentRescheduled: "Appointment rescheduled successfully",
    failedToReschedule: "Failed to reschedule appointment",
    appointmentCancelled: "Appointment cancelled successfully",
    failedToCancelAppointment: "Failed to cancel appointment",
    confirmCancelAppointment: "Are you sure you want to cancel this appointment?",
    failedToLoadAppointments: "Failed to load appointments",
    // Document Preview
    document: "Document",
    documentType: "Document Type",
    fileType: "File Type",
    downloadDocument: "Download Document",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    rotate: "Rotate",
    errorLoadingImage: "Error loading image",
    openInNewTab: "Open in New Tab",
    officeDocumentPreview: "Office Document Preview",
    officeDocumentPreviewDesc: "This document type requires downloading or opening in a new tab for viewing.",
    filePreviewNotAvailable: "File Preview Not Available",
    downloadToView: "Please download the file to view its contents.",
    // Analytics Dashboard
    analyticsOverview: "Analytics Overview",
    week: "Week",
    month: "Month",
    quarter: "Quarter",
    loadingAnalytics: "Loading analytics...",
    errorLoadingAnalytics: "Error loading analytics data",
    retry: "Retry",
    totalApplications: "Total Applications",
    approvedApplications: "Approved Applications",
    pendingReview: "Pending Review",
    totalAppointments: "Total Appointments",
    approvalRate: "approval rate",
    applicationStatusBreakdown: "Application Status Breakdown",
    pendingDocuments: "Pending Documents",
    documentStatus: "Document Status",
    monthlyApplications: "Monthly Applications",
    visaTypeDistribution: "Visa Type Distribution",
    processingTimeMetrics: "Processing Time Metrics",
    averageDays: "Average Days",
    fastestDays: "Fastest Days",
    slowestDays: "Slowest Days",
    // Messaging System
    messagingSystem: "Messaging System",
    conversations: "Conversations",
    noConversations: "No conversations found",
    selectConversation: "Select a conversation to start messaging",
    typeMessage: "Type your message...",
    send: "Send",
    sending: "Sending...",
    messageSent: "Message sent successfully",
    errorSendingMessage: "Error sending message",
    errorLoadingMessages: "Error loading messages",
    messages: "Messages",
    newMessage: "New Message",
    language: "Language",
    // Process Timeline
    applicationTimeline: "Application Timeline",
    applicationStarted: "Application Started",
    applicationStartedDesc: "Your visa application has been initiated and submitted to our system.",
    documentsUpload: "Documents Upload",
    documentsUploadDesc: "Upload and verify all required documents for your application.",
    reviewProcess: "Review Process",
    reviewProcessDesc: "Our team is reviewing your application and documents.",
    appointmentScheduling: "Appointment Scheduling",
    appointmentSchedulingDesc: "Schedule and attend your visa interview appointment.",
    finalDecision: "Final Decision",
    finalDecisionDesc: "Receive the final decision on your visa application.",
    currentStatus: "Current Status",
    estimatedReviewTime: "Estimated Review Time",
    businessDays: "business days",
    readyToSchedule: "Ready to schedule appointment",
    pendingApproval: "Pending application approval",
    date: "Date",
    time: "Time",
    location: "Location",
    visaProcessingComplete: "Visa processing is complete",
    contactSupportForDetails: "Contact support for more details",
    pendingFinalReview: "Pending final review after appointment",
    applicationSubmitted: "Application Submitted",
    inProgress: "In Progress",
    // New Application
    createNewApplication: "Create New Application",
    selectVisaTypeForNewApplication: "Select the type of visa you want to apply for",
    documentsRequired: "Documents Required",
    applicationSummary: "Application Summary",
    reviewBeforeSubmitting: "Please review the information before submitting your new application",
    selectedVisaType: "Selected Visa Type",
    documentsYouWillNeed: "Documents You Will Need",
    importantNotes: "Important Notes",
    allDocumentsMustBeValid: "All documents must be valid and not expired",
    processingTimeIs: "Processing time is",
    applicationFeeWillBeCharged: "Application fee will be charged upon submission",
    youCanTrackProgress: "You can track your application progress in the dashboard",
    back: "Back",
    createApplication: "Create Application",
    creating: "Creating",
    applicationCreatedSuccessfully: "Application created successfully",
    errorCreatingApplication: "Error creating application",
    passport: "Passport",
    birthCertificate: "Birth Certificate",
    identityDocument: "Identity Document",
    medicalCertificate: "Medical Certificate",
    familyDocuments: "Family Documents",
    sponsorshipLetter: "Sponsorship Letter",
    incomeProof: "Income Proof",
    humanitarianDocuments: "Humanitarian Documents",
    emergencyDocuments: "Emergency Documents",
    // User Management
    userManagement: "User Management",
    createNewUser: "Create New User",
    userRole: "User Role",
    applicant: "Applicant",
    administrator: "Administrator",
    sendWelcomeEmail: "Send welcome email",
    createUser: "Create User",
    userCreatedSuccessfully: "User created successfully",
    errorCreatingUser: "Error creating user",
    searchUsers: "Search users...",
    allRoles: "All Roles",
    user: "User",
    lastLogin: "Last Login",
    actions: "Actions",
    active: "Active",
    inactive: "Inactive",
    never: "Never",
    deactivate: "Deactivate",
    activate: "Activate",
    userDeactivated: "User deactivated successfully",
    userActivated: "User activated successfully",
    userRoleUpdated: "User role updated successfully",
    errorUpdatingUser: "Error updating user",
    errorLoadingUsers: "Error loading users",
    noUsersFound: "No users found",
    currentApplication: "Current Application",
    // Email Verification
    verifyingEmail: "Verifying Email",
    pleaseWait: "Please wait while we verify your email address...",
    emailVerified: "Email Verified Successfully",
    verificationFailed: "Email Verification Failed",
    alreadyVerifiedInfo: "Your email was already verified. You can proceed to login.",
    welcomeEmailSent: "A welcome email has been sent to your inbox.",
    goToLogin: "Go to Login",
    goToHome: "Go to Home",
    // New Application Messages
    welcomeMessage: "Welcome to CAVB Visa Application",
    noApplicationMessage: "You don't have any visa application yet. Start your visa application process now!",
    // Applications List
    myApplications: "My Applications",
    applicationsCount_one: "{{count}} application",
    applicationsCount_other: "{{count}} applications",
    noApplicationsYet: "No Applications Yet",
    noApplicationsMatch: "No Applications Match Filters",
    startFirstApplication: "Create your first visa application to get started",
    adjustFilters: "Try adjusting the filters to see more applications",
    filterByStatus: "Filter by Status",
    allStatuses: "All Statuses",
    sortBy: "Sort by",
    dateCreated: "Date Created",
    loadingApplications: "Loading applications",
    viewDetails: "View Details",
    expand: "Expand",
    collapse: "Collapse",
    documentsProgress: "Documents Progress",
    processTimeline: "Process Timeline",
    andXMore: "and {{count}} more...",
    at: " at ",
    exportPDF: "Export PDF",
    viewFullDetails: "View Full Details",
    // Application Management
    deleteApplication: "Delete Application",
    editApplication: "Edit Application",
    confirmDelete: "Are you sure you want to delete this application?",
    deleteWarning: "This action cannot be undone. All documents and data will be permanently removed.",
    cannotDeleteApproved: "Cannot delete approved applications or applications with scheduled appointments.",
    applicationDeleted: "Application deleted successfully",
    applicationsRemaining: "You can create {{count}} more applications ({{used}}/{{total}} used)",
    editVisaType: "Edit Visa Type",
    selectNewVisaType: "Select new visa type",
    confirmEdit: "Are you sure you want to change the visa type?",
    editWarning: "Changing visa type will reset all uploaded documents. You'll need to upload documents again based on new requirements.",
    cannotEditApproved: "Cannot edit approved applications or applications with scheduled appointments.",
    applicationUpdated: "Application updated successfully",
    // Application Details View
    goBack: "Go Back",
    overallProgress: "Overall Progress",
    submitted: "Submitted",
    documentsCompleted: "Documents Completed",
    documentColumn: "Document",
    fileNameColumn: "File Name",
    uploadDateColumn: "Upload Date",
    // Dashboard
    welcome: "Welcome",
    dashboardSubtitle: "Manage your visa applications and track their progress",
  },
  [Language.FR]: {
    // General
    appName: "OIM - Visa Brésil",
    login: "Connexion",
    register: "S'inscrire",
    logout: "Déconnexion",
    email: "Adresse e-mail",
    password: "Mot de passe",
    fullName: "Nom complet",
    submit: "Soumettre",
    loading: "Chargement...",
    // Plan Page
    planTitle: "Plan de Développement & Base de Données",
    planIntro: "Ce document présente le plan de développement et le schéma de base de données conceptuel pour la plateforme de demande de visa CAVB OIM Haïti Brésil, comme demandé.",
    devPlanTitle: "Plan de Développement",
    phase1: "Phase 1 : Fondation & Authentification",
    phase1Desc: "Construire l'interface utilisateur, le support multilingue, le portail d'authentification (Connexion/Inscription) et la structure de base des pages.",
    phase2: "Phase 2 : Tableau de Bord Utilisateur & Flux de Demande",
    phase2Desc: "Développer le tableau de bord utilisateur, la sélection du type de visa, le système de prise de rendez-vous et la fonctionnalité de téléchargement de documents.",
    phase3: "Phase 3 : Intégration Backend & Notifications",
    phase3Desc: "Connecter le frontend aux services backend, gérer les états de la demande et implémenter les systèmes de notification utilisateur.",
    dbSchemaTitle: "Schéma de Base de Données Conceptuel",
    dbSchemaDesc: "Un schéma simplifié pour supporter les fonctionnalités de l'application, axé sur les utilisateurs, les demandes, les documents et les rendez-vous.",
    usersTable: "Table des Utilisateurs",
    applicationsTable: "Table des Demandes",
    documentsTable: "Table des Documents",
    appointmentsTable: "Table des Rendez-vous",
    proceedToApp: "Accéder à la Démo de l'Application",
    // Home Page
    welcomeTitle: "Bienvenue sur le Portail de Demande de Visa pour le Brésil",
    welcomeSubtitle: "Faciliter les demandes de visa pour les citoyens haïtiens via l'OIM.",
    vitemXI: "VITEM XI - Visa de Regroupement Familial",
    vitemXIDesc: "Pour les personnes ayant des membres de leur famille résidant au Brésil. Ce visa vise à réunir les familles et à renforcer les liens sociaux.",
    vitemIII: "VITEM III - Visa Humanitaire",
    vitemIIIDesc: "Pour les ressortissants haïtiens confrontés à des crises humanitaires, tel qu'établi par les ordonnances interministérielles brésiliennes.",
    getStarted: "Commencer",
    // Dashboard
    dashboardTitle: "Mon Tableau de Bord de Demande",
    applicationStatus: "Statut de la Demande",
    applicationDetails: "Détails de la Demande",
    visaType: "Type de Visa",
    createdAt: "Date de soumission",
    documents: "Documents Requis",
    docType: "Type de Document",
    docStatus: "Statut",
    docAction: "Action",
    fileName: "Nom du Fichier",
    upload: "Télécharger",
    view: "Voir",
    appointment: "Votre Rendez-vous",
    noAppointment: "Aucun rendez-vous programmé pour le moment. Veuillez télécharger tous les documents requis pour continuer.",
    scheduleAppointment: "Prendre Rendez-vous",
    appointmentAt: "Rendez-vous à",
    appointmentPromptApproved: "Votre demande est approuvée. Veuillez programmer votre rendez-vous ci-dessous.",
    appointmentPromptReview: "Votre demande est en cours d'examen. Une fois approuvée, vous pourrez prendre rendez-vous.",
    applicationRejectedMessage: "Votre demande a été rejetée. Aucun rendez-vous ne peut être programmé.",
    // Statuses
    [ApplicationStatus.NOT_STARTED]: "Non Commencé",
    [ApplicationStatus.PENDING_DOCUMENTS]: "Documents en Attente",
    [ApplicationStatus.IN_REVIEW]: "En Cours d'Examen",
    [ApplicationStatus.APPOINTMENT_SCHEDULED]: "Rendez-vous Programmé",
    [ApplicationStatus.APPROVED]: "Approuvé",
    [ApplicationStatus.REJECTED]: "Rejeté",
    [DocumentStatus.MISSING]: "Manquant",
    [DocumentStatus.UPLOADED]: "Téléchargé",
    [DocumentStatus.VERIFIED]: "Vérifié",
    // Appointment Statuses
    [AppointmentStatus.BOOKED]: "Réservé",
    [AppointmentStatus.CONFIRMED]: "Confirmé",
    [AppointmentStatus.COMPLETED]: "Terminé",
    [AppointmentStatus.CANCELLED]: "Annulé",
    // Visa Types
    [VisaType.VITEM_XI]: "VITEM XI (Regroupement Familial)",
    [VisaType.VITEM_III]: "VITEM III (Humanitaire)",
    selectVisaType: "Sélectionnez Votre Programme de Visa",
    startApplication: "Commencer la Demande",
    // Auth
    authPrompt: "Veuillez vous connecter ou vous inscrire pour commencer votre demande.",
    loginPrompt: "Vous avez déjà un compte ?",
    registerPrompt: "Vous n'avez pas de compte ?",
    fillAllFields: "Veuillez remplir tous les champs.",
    invalidCredentials: "Email ou mot de passe invalide.",
    registrationSuccess: "Inscription réussie ! Veuillez vous connecter.",
    // Email verification
    registrationSuccessTitle: "Inscription Réussie !",
    accountCreatedMessage: "Votre compte a été créé avec succès. Pour compléter le processus d'inscription :",
    verifyEmailRequired: "Vérification d'Email Requise",
    emailVerificationStep1: "Allez dans votre boîte de réception Gmail",
    emailVerificationStep2: "Cherchez l'email de \"IOM Visa Application System\"",
    emailVerificationStep3: "Cliquez sur le bouton \"✅ Verify Email Address\"",
    emailVerificationStep4: "Une fois vérifié, vous pouvez vous connecter",
    emailSentTo: "Email envoyé à :",
    spamWarning: "⚠️ Si vous ne trouvez pas l'email, vérifiez votre dossier spam ou courrier indésirable.",
    gotItGoToLogin: "Compris, aller au Login",
    apiError: "Une erreur est survenue. Veuillez réessayer plus tard.",
    fileUploaded: "Fichier téléchargé avec succès.",
    appointmentBooked: "Rendez-vous pris avec succès.",
    // Enhanced Appointment Form
    dateOfBirth: "Date de Naissance",
    passportNumber: "Numéro de Passeport",
    nationality: "Nationalité",
    selectNationality: "Sélectionner Nationalité",
    appointmentDate: "Date du Rendez-vous",
    appointmentTime: "Heure du Rendez-vous",
    selectTime: "Sélectionner l'Heure",
    bookAppointment: "Prendre Rendez-vous",
    scheduling: "Planification...",
    appointmentRequirements: "Exigences du Rendez-vous",
    identityDocumentVerified: "Document d'Identité Vérifié",
    personalInfoComplete: "Informations Personnelles Complètes",
    identityDocumentRequired: "Le document d'identité doit être vérifié avant de prendre rendez-vous",
    appointmentBookingNote: "Veuillez vous assurer que toutes les informations sont correctes. Une lettre de confirmation sera générée après la réservation.",
    status: "Statut",
    downloadLetter: "Télécharger la Lettre",
    // Profile Page
    personalInformation: "Informations Personnelles",
    security: "Sécurité",
    phoneNumber: "Numéro de Téléphone",
    address: "Adresse",
    enterYourAddress: "Entrez votre adresse complète",
    updateProfile: "Mettre à jour le Profil",
    updating: "Mise à jour...",
    profileUpdatedSuccessfully: "Profil mis à jour avec succès",
    profileUpdateFailed: "Échec de la mise à jour du profil",
    currentPassword: "Mot de Passe Actuel",
    newPassword: "Nouveau Mot de Passe",
    confirmNewPassword: "Confirmer le Nouveau Mot de Passe",
    changePassword: "Changer le Mot de Passe",
    passwordsDoNotMatch: "Les mots de passe ne correspondent pas",
    passwordTooShort: "Le mot de passe doit comporter au moins 6 caractères",
    passwordChangedSuccessfully: "Mot de passe changé avec succès",
    passwordChangeFailed: "Échec du changement de mot de passe",
    passwordSecurityNote: "Sécurité du Mot de Passe",
    passwordRequirements: "Votre mot de passe doit comporter au moins 6 caractères et contenir un mélange de lettres et de chiffres.",
    imageTooLarge: "Le fichier image est trop volumineux. Taille maximale 5MB.",
    // Admin
    adminDashboard: "Tableau de Bord Admin",
    allApplications: "Toutes les Demandes",
    applicantName: "Nom du Demandeur",
    applicantEmail: "Email du Demandeur",
    applicationId: "ID de la Demande",
    reviewApplication: "Examiner la Demande",
    updateStatus: "Mettre à jour le Statut",
    approve: "Approuver",
    reject: "Rejeter",
    verify: "Vérifier",
    rejectionReason: "Motif du Rejet",
    rejectionReasonPrompt: "Veuillez fournir un motif pour le rejet.",
    cancel: "Annuler",
    confirm: "Confirmer",
    documentVerified: "Document Vérifié.",
    documentRejected: "Document Rejeté.",
    applicationApproved: "Demande Approuvée.",
    applicationRejected: "Demande Rejetée.",
    manageApplication: "Gérer la Demande",
    approveApplication: "Approuver la Demande",
    rejectApplication: "Rejeter la Demande",
    documentReview: "Examen des Documents",
    noApplications: "Aucune demande trouvée.",
    rejectionNote: "Motif du Rejet",
    // Calendar & Appointments
    appointmentManagement: "Gestion des Rendez-vous",
    calendar: "Calendrier",
    list: "Liste",
    january: "Janvier",
    february: "Février",
    march: "Mars",
    april: "Avril",
    may: "Mai",
    june: "Juin",
    july: "Juillet",
    august: "Août",
    september: "Septembre",
    october: "Octobre",
    november: "Novembre",
    december: "Décembre",
    sunday: "Dimanche",
    monday: "Lundi",
    tuesday: "Mardi",
    wednesday: "Mercredi",
    thursday: "Jeudi",
    friday: "Vendredi",
    saturday: "Samedi",
    more: "plus",
    appointmentsFor: "Rendez-vous pour",
    noAppointmentsScheduled: "Aucun rendez-vous programmé",
    reschedule: "Reporter",
    rescheduleAppointment: "Reporter le Rendez-vous",
    newDate: "Nouvelle Date",
    newTime: "Nouvelle Heure",
    appointmentRescheduled: "Rendez-vous reporté avec succès",
    failedToReschedule: "Échec du report du rendez-vous",
    appointmentCancelled: "Rendez-vous annulé avec succès",
    failedToCancelAppointment: "Échec de l'annulation du rendez-vous",
    confirmCancelAppointment: "Êtes-vous sûr de vouloir annuler ce rendez-vous?",
    failedToLoadAppointments: "Échec du chargement des rendez-vous",
    // Document Preview
    document: "Document",
    documentType: "Type de Document",
    fileType: "Type de Fichier",
    downloadDocument: "Télécharger le Document",
    zoomIn: "Zoomer",
    zoomOut: "Dézoomer",
    rotate: "Rotation",
    errorLoadingImage: "Erreur de chargement de l'image",
    openInNewTab: "Ouvrir dans un Nouvel Onglet",
    officeDocumentPreview: "Aperçu Document Office",
    officeDocumentPreviewDesc: "Ce type de document nécessite d'être téléchargé ou ouvert dans un nouvel onglet pour être consulté.",
    filePreviewNotAvailable: "Aperçu de Fichier Non Disponible",
    downloadToView: "Veuillez télécharger le fichier pour voir son contenu.",
    // Analytics Dashboard
    analyticsOverview: "Vue d'ensemble Analytique",
    week: "Semaine",
    month: "Mois",
    quarter: "Trimestre",
    loadingAnalytics: "Chargement des analyses...",
    errorLoadingAnalytics: "Erreur de chargement des données analytiques",
    retry: "Réessayer",
    totalApplications: "Total des Demandes",
    approvedApplications: "Demandes Approuvées",
    pendingReview: "En Attente d'Examen",
    totalAppointments: "Total des Rendez-vous",
    approvalRate: "taux d'approbation",
    applicationStatusBreakdown: "Répartition des Statuts de Demande",
    pendingDocuments: "Documents en Attente",
    documentStatus: "Statut des Documents",
    monthlyApplications: "Demandes Mensuelles",
    visaTypeDistribution: "Distribution par Type de Visa",
    processingTimeMetrics: "Métriques de Temps de Traitement",
    averageDays: "Jours Moyens",
    fastestDays: "Jours les Plus Rapides",
    slowestDays: "Jours les Plus Lents",
    // Messaging System
    messagingSystem: "Système de Messagerie",
    conversations: "Conversations",
    noConversations: "Aucune conversation trouvée",
    selectConversation: "Sélectionnez une conversation pour commencer à envoyer des messages",
    typeMessage: "Tapez votre message...",
    send: "Envoyer",
    sending: "Envoi en cours...",
    messageSent: "Message envoyé avec succès",
    errorSendingMessage: "Erreur lors de l'envoi du message",
    errorLoadingMessages: "Erreur lors du chargement des messages",
    messages: "Messages",
    newMessage: "Nouveau Message",
    language: "Langue",
    // Email Verification
    verifyingEmail: "Vérification de l'Email",
    pleaseWait: "Veuillez patienter pendant que nous vérifions votre adresse email...",
    emailVerified: "Email Vérifié avec Succès",
    verificationFailed: "Échec de la Vérification Email",
    alreadyVerifiedInfo: "Votre email était déjà vérifié. Vous pouvez procéder à la connexion.",
    welcomeEmailSent: "Un email de bienvenue a été envoyé à votre boîte de réception.",
    goToLogin: "Aller à la Connexion",
    goToHome: "Aller à l'Accueil",
    // New Application Messages
    welcomeMessage: "Bienvenue à la Demande de Visa CAVB",
    noApplicationMessage: "Vous n'avez pas encore de demande de visa. Commencez votre processus de demande de visa maintenant!",
    // Applications List
    myApplications: "Mes Demandes",
    applicationsCount_one: "{{count}} demande",
    applicationsCount_other: "{{count}} demandes",
    noApplicationsYet: "Aucune Demande Encore",
    noApplicationsMatch: "Aucune Demande ne Correspond aux Filtres",
    startFirstApplication: "Créez votre première demande de visa pour commencer",
    adjustFilters: "Essayez d'ajuster les filtres pour voir plus de demandes",
    filterByStatus: "Filtrer par Statut",
    allStatuses: "Tous les Statuts",
    sortBy: "Trier par",
    dateCreated: "Date de Création",
    loadingApplications: "Chargement des demandes",
    viewDetails: "Voir les Détails",
    expand: "Développer",
    collapse: "Réduire",
    documentsProgress: "Progrès des Documents",
    processTimeline: "Chronologie du Processus",
    andXMore: "et {{count}} de plus...",
    at: " à ",
    exportPDF: "Exporter PDF",
    viewFullDetails: "Voir Tous les Détails",
    // Application Management
    deleteApplication: "Supprimer la Demande",
    editApplication: "Modifier la Demande",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer cette demande ?",
    deleteWarning: "Cette action ne peut pas être annulée. Tous les documents et données seront définitivement supprimés.",
    cannotDeleteApproved: "Impossible de supprimer les demandes approuvées ou celles avec rendez-vous programmé.",
    applicationDeleted: "Demande supprimée avec succès",
    applicationsRemaining: "Vous pouvez créer {{count}} demandes de plus ({{used}}/{{total}} utilisées)",
    editVisaType: "Modifier le Type de Visa",
    selectNewVisaType: "Sélectionnez le nouveau type de visa",
    confirmEdit: "Êtes-vous sûr de vouloir changer le type de visa ?",
    editWarning: "Changer le type de visa réinitialisera tous les documents téléchargés. Vous devrez télécharger les documents à nouveau selon les nouvelles exigences.",
    cannotEditApproved: "Impossible de modifier les demandes approuvées ou celles avec rendez-vous programmé.",
    applicationUpdated: "Demande mise à jour avec succès",
  },
  [Language.HT]: {
    // General
    appName: "OIM - Viza Brezil",
    login: "Konekte",
    register: "Anrejistre",
    logout: "Dekonekte",
    email: "Adrès Imèl",
    password: "Modpas",
    fullName: "Non Konplè",
    submit: "Soumèt",
    loading: "Chaje...",
    // Plan Page
    planTitle: "Plan Devlopman & Baz Done",
    planIntro: "Dokiman sa a dekri plan devlopman ak chema baz done konseptyèl pou platfòm aplikasyon viza CAVB OIM Ayiti Brezil la, jan yo te mande sa.",
    devPlanTitle: "Plan Devlopman",
    phase1: "Faz 1: Fondasyon Debaz & Otantifikasyon",
    phase1Desc: "Bati entèfas itilizatè a, sipò plizyè lang, pòtal otantifikasyon (Koneksyon/Enskripsyon), ak estrikti paj debaz.",
    phase2: "Faz 2: Tablo Bò Itilizatè & Pwosesis Aplikasyon",
    phase2Desc: "Devlope tablo bò itilizatè a, seleksyon kalite viza, sistèm pou pran randevou, ak fonksyonalite pou telechaje dokiman.",
    phase3: "Faz 3: Entegrasyon Backend & Notifikasyon",
    phase3Desc: "Konekte frontend la ak sèvis backend yo, jere estati aplikasyon yo, epi aplike sistèm notifikasyon pou itilizatè yo.",
    dbSchemaTitle: "Chema Baz Done Konseptyèl",
    dbSchemaDesc: "Yon chema senplifye pou sipòte fonksyonalite aplikasyon an, ki konsantre sou itilizatè, aplikasyon, dokiman, ak randevou.",
    usersTable: "Tab Itilizatè yo",
    applicationsTable: "Tab Aplikasyon yo",
    documentsTable: "Tab Dokiman yo",
    appointmentsTable: "Tab Randevou yo",
    proceedToApp: "Ale nan Demo Aplikasyon an",
    // Home Page
    welcomeTitle: "Byenveni nan Pòtal Aplikasyon Viza pou Brezil",
    welcomeSubtitle: "Fasilite demann viza pou sitwayen ayisyen atravè OIM.",
    vitemXI: "VITEM XI - Viza Reyinifikasyon Familyal",
    vitemXIDesc: "Pou moun ki gen manm fanmi yo k ap viv nan Brezil. Viza sa a gen pou objektif reyini fanmi yo epi ranfòse lyen sosyal yo.",
    vitemIII: "VITEM III - Viza Imanitè",
    vitemIIIDesc: "Pou sitwayen ayisyen k ap fè fas ak kriz imanitè, jan sa etabli nan òdonans entèministeryèl brezilyen yo.",
    getStarted: "Kòmanse",
    // Dashboard
    dashboardTitle: "Tablo Bò Aplikasyon Mwen an",
    applicationStatus: "Estati Aplikasyon an",
    applicationDetails: "Detay Aplikasyon an",
    visaType: "Kalite Viza",
    createdAt: "Dat Soumisyon",
    documents: "Dokiman Obligatwa",
    docType: "Kalite Dokiman",
    docStatus: "Estati",
    docAction: "Aksyon",
    fileName: "Non Fichye a",
    upload: "Telechaje",
    view: "Gade",
    appointment: "Randevou Ou",
    noAppointment: "Pa gen randevou pwograme pou kounye a. Tanpri telechaje tout dokiman ki nesesè yo pou w kontinye.",
    scheduleAppointment: "Pran Randevou",
    appointmentAt: "Randevou nan",
    appointmentPromptApproved: "Aplikasyon w la apwouve. Tanpri pwograme randevou w anba a.",
    appointmentPromptReview: "Aplikasyon w lan ap revize. Yon fwa yo apwouve l, w ap kapab pran yon randevou.",
    applicationRejectedMessage: "Aplikasyon w lan te rejte. Pa gen randevou ki ka pwograme.",
    // Statuses
    [ApplicationStatus.NOT_STARTED]: "Pa Kòmanse",
    [ApplicationStatus.PENDING_DOCUMENTS]: "Dokiman an Atant",
    [ApplicationStatus.IN_REVIEW]: "Ap Revize",
    [ApplicationStatus.APPOINTMENT_SCHEDULED]: "Randevou Pwograme",
    [ApplicationStatus.APPROVED]: "Apwouve",
    [ApplicationStatus.REJECTED]: "Rejte",
    [DocumentStatus.MISSING]: "Manke",
    [DocumentStatus.UPLOADED]: "Telechaje",
    [DocumentStatus.VERIFIED]: "Verifye",
    // Appointment Statuses
    [AppointmentStatus.BOOKED]: "Rezève",
    [AppointmentStatus.CONFIRMED]: "Konfime",
    [AppointmentStatus.COMPLETED]: "Fini",
    [AppointmentStatus.CANCELLED]: "Anile",
    // Visa Types
    [VisaType.VITEM_XI]: "VITEM XI (Reyinifikasyon Familyal)",
    [VisaType.VITEM_III]: "VITEM III (Imanitè)",
    selectVisaType: "Chwazi Pwogram Viza Ou",
    startApplication: "Kòmanse Aplikasyon an",
    // Auth
    authPrompt: "Tanpri konekte oswa anrejistre pou kòmanse aplikasyon w lan.",
    loginPrompt: "Ou gen yon kont deja?",
    registerPrompt: "Ou pa gen kont?",
    fillAllFields: "Tanpri ranpli tout chan yo.",
    invalidCredentials: "Imèl oswa modpas pa valab.",
    registrationSuccess: "Anrejistreman reyisi! Tanpri konekte.",
    // Email verification
    registrationSuccessTitle: "Anrejistreman Reyisi!",
    accountCreatedMessage: "Kont ou an kreye avèk siksè. Pou fini pwosè anrejistreman an:",
    verifyEmailRequired: "Verifikasyon Imèl Obligatwa",
    emailVerificationStep1: "Ale nan bwat resepsyon Gmail ou an",
    emailVerificationStep2: "Chèche imèl ki soti nan \"IOM Visa Application System\"",
    emailVerificationStep3: "Klike sou bouton \"✅ Verify Email Address\" la",
    emailVerificationStep4: "Yon fwa ou verifye, ou ka konekte",
    emailSentTo: "Imèl voye bay:",
    spamWarning: "⚠️ Si ou pa jwenn imèl la, gade nan dosye spam oswa courier ki pa vle.",
    gotItGoToLogin: "Konprann, ale nan Login",
    apiError: "Gen yon erè ki rive. Tanpri eseye ankò pita.",
    fileUploaded: "Fichye telechaje avèk siksè.",
    appointmentBooked: "Randevou pran avèk siksè.",
    // Enhanced Appointment Form
    dateOfBirth: "Dat Nesans",
    passportNumber: "Nimewo Paspò",
    nationality: "Nasyonalite",
    selectNationality: "Chwazi Nasyonalite",
    appointmentDate: "Dat Randevou",
    appointmentTime: "Lè Randevou",
    selectTime: "Chwazi Lè",
    bookAppointment: "Pran Randevou",
    scheduling: "Ap Pwograme...",
    appointmentRequirements: "Egzijans Randevou",
    identityDocumentVerified: "Dokiman Idantite Verifye",
    personalInfoComplete: "Enfòmasyon Pèsonèl Konple",
    identityDocumentRequired: "Dokiman idantite a dwe verifye anvan w pran randevou",
    appointmentBookingNote: "Tanpri asire w tout enfòmasyon yo kòrèk. Yo ap jenere yon lèt konfimasyon apre rezèvasyon an.",
    status: "Estati",
    downloadLetter: "Telechaje Lèt la",
    // Profile Page
    personalInformation: "Enfòmasyon Pèsonèl",
    security: "Sekirite",
    phoneNumber: "Nimewo Telefòn",
    address: "Adrès",
    enterYourAddress: "Antre adrès konple ou a",
    updateProfile: "Mete Pwofil la ajou",
    updating: "Ap mete ajou...",
    profileUpdatedSuccessfully: "Pwofil la mete ajou ak siksè",
    profileUpdateFailed: "Pa t kapab mete pwofil la ajou",
    currentPassword: "Modpas Aktyèl la",
    newPassword: "Nouvo Modpas",
    confirmNewPassword: "Konfime Nouvo Modpas la",
    changePassword: "Chanje Modpas",
    passwordsDoNotMatch: "Modpas yo pa menm",
    passwordTooShort: "Modpas la dwe gen omwen 6 karaktè",
    passwordChangedSuccessfully: "Modpas la chanje ak siksè",
    passwordChangeFailed: "Pa t kapab chanje modpas la",
    passwordSecurityNote: "Sekirite Modpas",
    passwordRequirements: "Modpas ou a dwe gen omwen 6 karaktè ak yon melanj lèt ak chif yo.",
    imageTooLarge: "Fichye foto a twò gwo. Gwosè maksimòm 5MB.",
    // Admin
    adminDashboard: "Tablo Bò Admin",
    allApplications: "Tout Aplikasyon yo",
    applicantName: "Non Aplikan an",
    applicantEmail: "Imèl Aplikan an",
    applicationId: "ID Aplikasyon",
    reviewApplication: "Revize Aplikasyon an",
    updateStatus: "Mete Estati a ajou",
    approve: "Apwouve",
    reject: "Rejte",
    verify: "Verifye",
    rejectionReason: "Rezon pou Rejè",
    rejectionReasonPrompt: "Tanpri bay yon rezon pou rejè a.",
    cancel: "Anile",
    confirm: "Konfime",
    documentVerified: "Dokiman Verifye.",
    documentRejected: "Dokiman Rejte.",
    applicationApproved: "Aplikasyon Apwouve.",
    applicationRejected: "Aplikasyon Rejte.",
    manageApplication: "Jere Aplikasyon an",
    approveApplication: "Apwouve Aplikasyon an",
    rejectApplication: "Rejte Aplikasyon an",
    documentReview: "Revizyon Dokiman",
    noApplications: "Pa gen okenn aplikasyon jwenn.",
    rejectionNote: "Rezon pou Rejè",
    // Calendar & Appointments
    appointmentManagement: "Jesyon Randevou yo",
    calendar: "Kalandriye",
    list: "Lis",
    january: "Janvye",
    february: "Fevrye",
    march: "Mas",
    april: "Avril",
    may: "Me",
    june: "Jen",
    july: "Jiyè",
    august: "Dawou",
    september: "Septanm",
    october: "Oktòb",
    november: "Novanm",
    december: "Desanm",
    sunday: "Dimanch",
    monday: "Lendi",
    tuesday: "Madi",
    wednesday: "Mèkredi",
    thursday: "Jedi",
    friday: "Vandredi",
    saturday: "Samdi",
    more: "plis",
    appointmentsFor: "Randevou pou",
    noAppointmentsScheduled: "Pa gen randevou pwograme",
    reschedule: "Chanje Dat",
    rescheduleAppointment: "Chanje Dat Randevou",
    newDate: "Nouvo Dat",
    newTime: "Nouvo Lè",
    appointmentRescheduled: "Randevou chanje dat ak siksè",
    failedToReschedule: "Pa t kapab chanje dat randevou a",
    appointmentCancelled: "Randevou anile ak siksè",
    failedToCancelAppointment: "Pa t kapab anile randevou a",
    confirmCancelAppointment: "Ou kwè w vle anile randevou sa a?",
    failedToLoadAppointments: "Pa t kapab chaje randevou yo",
    // Document Preview
    document: "Dokiman",
    documentType: "Kalite Dokiman",
    fileType: "Kalite Fichye",
    downloadDocument: "Telechaje Dokiman an",
    zoomIn: "Vin pi gwo",
    zoomOut: "Vin pi piti",
    rotate: "Vire",
    errorLoadingImage: "Erè nan chajman foto a",
    openInNewTab: "Ouvè nan nouvo tab",
    officeDocumentPreview: "Aperçu Dokiman Biwo",
    officeDocumentPreviewDesc: "Kalite dokiman sa a bezwen telechaje oswa ouvè nan yon nouvo tab pou gade l.",
    filePreviewNotAvailable: "Aperçu Fichye pa Disponib",
    downloadToView: "Tanpri telechaje fichye a pou w gade sa ki ladan l.",
    // Analytics Dashboard
    analyticsOverview: "Aperçu Analitik",
    week: "Semenn",
    month: "Mwa",
    quarter: "Twa Mwa",
    loadingAnalytics: "Ap chaje analiz yo...",
    errorLoadingAnalytics: "Erè nan chajman done analitik yo",
    retry: "Eseye Ankò",
    totalApplications: "Total Aplikasyon yo",
    approvedApplications: "Aplikasyon Apwouve yo",
    pendingReview: "Ap Tann Revizyon",
    totalAppointments: "Total Randevou yo",
    approvalRate: "to aprobrasyon",
    applicationStatusBreakdown: "Depo Estati Aplikasyon yo",
    pendingDocuments: "Dokiman ki nan Atant",
    documentStatus: "Estati Dokiman",
    monthlyApplications: "Aplikasyon nan Mwa",
    visaTypeDistribution: "Distribisyon pa Kalite Viza",
    processingTimeMetrics: "Metrik Tan Pwosesis",
    averageDays: "Jou Mwayèn",
    fastestDays: "Jou ki pi Vit",
    slowestDays: "Jou ki pi Dousman",
    // Messaging System
    messagingSystem: "Sistèm Mesaj",
    conversations: "Konvèsasyon yo",
    noConversations: "Pa gen okenn konvèsasyon jwenn",
    selectConversation: "Chwazi yon konvèsasyon pou kòmanse voye mesaj",
    typeMessage: "Tape mesaj ou a...",
    send: "Voye",
    sending: "Ap voye...",
    messageSent: "Mesaj voye ak siksè",
    errorSendingMessage: "Erè nan vwaye mesaj la",
    errorLoadingMessages: "Erè nan chajman mesaj yo",
    messages: "Mesaj yo",
    newMessage: "Nouvo Mesaj",
    language: "Lang",
    // Email Verification
    verifyingEmail: "Ap Verifye Imèl la",
    pleaseWait: "Tanpri tann pandan n ap verifye adrès imèl ou a...",
    emailVerified: "Imèl Verifye ak Siksè",
    verificationFailed: "Verifikasyon Imèl la Echwe",
    alreadyVerifiedInfo: "Imèl ou a te deja verifye. Ou ka ale nan koneksyon an.",
    welcomeEmailSent: "Yo voye yon imèl bienveni nan bwat imèl ou a.",
    goToLogin: "Ale nan Koneksyon",
    goToHome: "Ale nan Akèy",
    // New Application Messages
    welcomeMessage: "Byenvini nan Demann Viza CAVB la",
    noApplicationMessage: "Ou pa gen okenn demann viza ankò. Kòmanse pwosèdi demann viza ou a kounye a!",
    // Applications List
    myApplications: "Demann Mwen Yo",
    applicationsCount_one: "{{count}} demann",
    applicationsCount_other: "{{count}} demann yo",
    noApplicationsYet: "Pa gen Demann Ankò",
    noApplicationsMatch: "Pa gen Demann ki Matche ak Filtè yo",
    startFirstApplication: "Kreye premye demann viza ou a pou kòmanse",
    adjustFilters: "Eseye ajiste filtè yo pou wè plis demann",
    filterByStatus: "Filtè pa Estati",
    allStatuses: "Tout Estati yo",
    sortBy: "Klase pa",
    dateCreated: "Dat Kreyasyon",
    loadingApplications: "Ap chaje demann yo",
    viewDetails: "Gade Detay yo",
    expand: "Ouvè",
    collapse: "Fèmen",
    documentsProgress: "Pwogrè Dokiman yo",
    processTimeline: "Òd tan Pwosèdi a",
    andXMore: "ak {{count}} plis...",
    at: " nan ",
    exportPDF: "Ekspòte PDF",
    viewFullDetails: "Gade Tout Detay yo",
    // Application Management
    deleteApplication: "Efase Demann lan",
    editApplication: "Modifye Demann lan",
    confirmDelete: "Èske ou si ou vle efase demann sa a?",
    deleteWarning: "Aksyon sa a pa ka defè. Tout dokiman ak done yo ap efase pou tout tan.",
    cannotDeleteApproved: "Pa ka efase demann ki apwouve yo oswa sa yo ki gen randevou pwograme.",
    applicationDeleted: "Demann lan efase ak siksè",
    applicationsRemaining: "Ou ka kreye {{count}} demann ankò ({{used}}/{{total}} yo itilize)",
    editVisaType: "Modifye Kalite Viza a",
    selectNewVisaType: "Chwazi nouvo kalite viza a",
    confirmEdit: "Èske ou si ou vle chanje kalite viza a?",
    editWarning: "Chanje kalite viza a ap efase tout dokiman yo. Ou ap oblije telechaje dokiman yo ankò selon nouvo kondisyon yo.",
    cannotEditApproved: "Pa ka modifye demann ki apwouve yo oswa sa yo ki gen randevou pwograme.",
    applicationUpdated: "Demann lan modifye ak siksè",
  }
};