version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: visa-app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: visa_application_db
      MYSQL_USER: visa_user
      MYSQL_PASSWORD: visa_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: